name: iOS CD

on:
  pull_request:
    branches: 
      - develop

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Install bundler
      run: gem install bundler

    - name: Install fastlane
      run: bundle install
      working-directory: ./InstagramClone

    - name: Running test
      run: bundle exec fastlane test_app