name: iOS CD

on:
  pull_request:
    branches: 
      - develop

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
    - name: Running test
	run: xcodebuild test --workspace InstagramClone.xcworkspace -scheme InstagramClone
	working-directory: ./InstagramClone