name: iOS CD

on:
  pull_request:
    branches: 
      - develop

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Running test
	run: xcodebuild test --workspace InstagramClone.xcworkspace -scheme InstagramClone
	working-directory: ./InstagramClone