name: iOS CD

on:
  pull_request:
    branches: 
      - develop

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Running test
	run: xcodebuild test -workspace InstagramClone.xcworkspace -scheme InstagramClone -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' ONLY_ACTIVE_ARCH=YES -quiet
	working-directory: ./InstagramClone